///~~~ ESOTERIC UNICODE MESSAGE ~~~///
//    |* the following is a pure seculative 
//    |* reading of the values of the fexp
//    |* also known as experimental flags
//    |* and its translation in MIDI
//    |* compatible values
///~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~///

[[{ hex: '00DB', meaning: 'LATIN CAPITAL LETTER U CIRCUMFLEX' },
{ hex: '007E', meaning: 'TILDE' },
{ hex: '00F4', meaning: 'LATIN SMALL LETTER O CIRCUMFLEX' },
{ hex: '00DF', meaning: 'LATIN SMALL LETTER SHARP S' },
{ hex: '008E', meaning: 'SINGLE SHIFT TWO' },
{ hex: '0039', meaning: 'DIGIT NINE' }],
[{ hex: '00DB', meaning: 'LATIN CAPITAL LETTER U CIRCUMFLEX' },
{ hex: '007F', meaning: 'DELETE' },
{ hex: '007C', meaning: 'VERTICAL BAR' },
{ hex: '00DF', meaning: 'LATIN SMALL LETTER SHARP S' },
{ hex: '006F', meaning: 'LATIN SMALL LETTER O' },
{ hex: '007A', meaning: 'LATIN SMALL LETTER Z' }],
[{ hex: '00DB', meaning: 'LATIN CAPITAL LETTER U CIRCUMFLEX' },
{ hex: '007F', meaning: 'DELETE' },
{ hex: '007C', meaning: 'VERTICAL BAR' },
{ hex: '00EB', meaning: 'LATIN SMALL LETTER E DIAERESIS' },
{ hex: '004D', meaning: 'LATIN CAPITAL LETTER M' },
{ hex: '00B7', meaning: 'MIDDLE DOT' }],
[{ hex: '00DB', meaning: 'LATIN CAPITAL LETTER U CIRCUMFLEX' },
{ hex: '008D', meaning: 'REVERSE LINE FEED' },
{ hex: '0034', meaning: 'DIGIT FOUR' },
{ hex: '00D7', meaning: 'MULTIPLICATION SIGN' },
{ hex: '007E', meaning: 'TILDE' },
{ hex: '00F7', meaning: 'DIVISION SIGN' }],
[{ hex: '00DB', meaning: 'LATIN CAPITAL LETTER U CIRCUMFLEX' },
{ hex: '008D', meaning: 'REVERSE LINE FEED' },
{ hex: '0034', meaning: 'DIGIT FOUR' },
{ hex: '00DB', meaning: 'LATIN CAPITAL LETTER U CIRCUMFLEX' },
{ hex: '004D', meaning: 'LATIN CAPITAL LETTER M' },
{ hex: '00B6', meaning: 'PARAGRAPH SIGN' }],
[{ hex: '00DB', meaning: 'LATIN CAPITAL LETTER U CIRCUMFLEX' },
{ hex: '008D', meaning: 'REVERSE LINE FEED' },
{ hex: '0034', meaning: 'DIGIT FOUR' },
{ hex: '00DB', meaning: 'LATIN CAPITAL LETTER U CIRCUMFLEX' },
{ hex: '004D', meaning: 'LATIN CAPITAL LETTER M' },
{ hex: '00B9', meaning: 'SUPERSCRIPT DIGIT ONE' }],
[{ hex: '00DB', meaning: 'LATIN CAPITAL LETTER U CIRCUMFLEX' },
{ hex: '008D', meaning: 'REVERSE LINE FEED' },
{ hex: '0034', meaning: 'DIGIT FOUR' },
{ hex: '00DB', meaning: 'LATIN CAPITAL LETTER U CIRCUMFLEX' },
{ hex: '00DD', meaning: 'LATIN CAPITAL LETTER Y ACUTE' },
{ hex: '00B6', meaning: 'PARAGRAPH SIGN' }],
[{ hex: '00DB', meaning: 'LATIN CAPITAL LETTER U CIRCUMFLEX' },
{ hex: '008D', meaning: 'REVERSE LINE FEED' },
{ hex: '0034', meaning: 'DIGIT FOUR' },
{ hex: '00E3', meaning: 'LATIN SMALL LETTER A TILDE' },
{ hex: '00AE', meaning: 'REGISTERED TRADE MARK SIGN' },
{ hex: '0038', meaning: 'DIGIT EIGHT' }],
[{ hex: '00DB', meaning: 'LATIN CAPITAL LETTER U CIRCUMFLEX' },
{ hex: '008D', meaning: 'REVERSE LINE FEED' },
{ hex: '0034', meaning: 'DIGIT FOUR' },
{ hex: '00EF', meaning: 'LATIN SMALL LETTER I DIAERESIS' },
{ hex: '006E', meaning: 'LATIN SMALL LETTER N' },
{ hex: '003A', meaning: 'COLON' }],
[{ hex: '00DB', meaning: 'LATIN CAPITAL LETTER U CIRCUMFLEX' },
{ hex: '008D', meaning: 'REVERSE LINE FEED' },
{ hex: '003A', meaning: 'COLON' },
{ hex: '00E3', meaning: 'LATIN SMALL LETTER A TILDE' },
{ hex: '009E', meaning: 'PRIVACY MESSAGE' },
{ hex: '0079', meaning: 'LATIN SMALL LETTER Y' }],
[{ hex: '00DB', meaning: 'LATIN CAPITAL LETTER U CIRCUMFLEX' },
{ hex: '008D', meaning: 'REVERSE LINE FEED' },
{ hex: '003C', meaning: 'LESS-THAN SIGN' },
{ hex: '00D3', meaning: 'LATIN CAPITAL LETTER O ACUTE' },
{ hex: '00BD', meaning: 'FRACTION ONE HALF' },
{ hex: '00FC', meaning: 'LATIN SMALL LETTER U DIAERESIS' }],
[{ hex: '00DB', meaning: 'LATIN CAPITAL LETTER U CIRCUMFLEX' },
{ hex: '008D', meaning: 'REVERSE LINE FEED' },
{ hex: '003C', meaning: 'LESS-THAN SIGN' },
{ hex: '00DB', meaning: 'LATIN CAPITAL LETTER U CIRCUMFLEX' },
{ hex: '00AE', meaning: 'REGISTERED TRADE MARK SIGN' },
{ hex: '00B5', meaning: 'MICRO SIGN' }],
[{ hex: '00DB', meaning: 'LATIN CAPITAL LETTER U CIRCUMFLEX' },
{ hex: '008D', meaning: 'REVERSE LINE FEED' },
{ hex: '0074', meaning: 'LATIN SMALL LETTER T' },
{ hex: '00DB', meaning: 'LATIN CAPITAL LETTER U CIRCUMFLEX' },
{ hex: '005D', meaning: 'CLOSING SQUARE BRACKET' },
{ hex: '00B4', meaning: 'SPACING ACUTE' }],
[{ hex: '00DB', meaning: 'LATIN CAPITAL LETTER U CIRCUMFLEX' },
{ hex: '008D', meaning: 'REVERSE LINE FEED' },
{ hex: '0074', meaning: 'LATIN SMALL LETTER T' },
{ hex: '00E3', meaning: 'LATIN SMALL LETTER A TILDE' },
{ hex: '00AD', meaning: 'SOFT HYPHEN' },
{ hex: '007C', meaning: 'VERTICAL BAR' }],
[{ hex: '00DB', meaning: 'LATIN CAPITAL LETTER U CIRCUMFLEX' },
{ hex: '008D', meaning: 'REVERSE LINE FEED' },
{ hex: '0075', meaning: 'LATIN SMALL LETTER U' },
{ hex: '00E7', meaning: 'LATIN SMALL LETTER C CEDILLA' },
{ hex: '009D', meaning: 'OPERATING SYSTEM COMMAND' },
{ hex: '003C', meaning: 'LESS-THAN SIGN' }],
[{ hex: '00DB', meaning: 'LATIN CAPITAL LETTER U CIRCUMFLEX' },
{ hex: '008D', meaning: 'REVERSE LINE FEED' },
{ hex: '0075', meaning: 'LATIN SMALL LETTER U' },
{ hex: '00E7', meaning: 'LATIN SMALL LETTER C CEDILLA' },
{ hex: '009F', meaning: 'APPLICATION PROGRAM COMMAND' },
{ hex: '003A', meaning: 'COLON' }],
[{ hex: '00DB', meaning: 'LATIN CAPITAL LETTER U CIRCUMFLEX' },
{ hex: '008D', meaning: 'REVERSE LINE FEED' },
{ hex: '0075', meaning: 'LATIN SMALL LETTER U' },
{ hex: '00F3', meaning: 'LATIN SMALL LETTER O ACUTE' },
{ hex: '009D', meaning: 'OPERATING SYSTEM COMMAND' },
{ hex: '007C', meaning: 'VERTICAL BAR' }],
[{ hex: '00DB', meaning: 'LATIN CAPITAL LETTER U CIRCUMFLEX' },
{ hex: '008D', meaning: 'REVERSE LINE FEED' },
{ hex: '0076', meaning: 'LATIN SMALL LETTER V' },
{ hex: '00E7', meaning: 'LATIN SMALL LETTER C CEDILLA' },
{ hex: '006E', meaning: 'LATIN SMALL LETTER N' },
{ hex: '00F4', meaning: 'LATIN SMALL LETTER O CIRCUMFLEX' }],
[{ hex: '00DB', meaning: 'LATIN CAPITAL LETTER U CIRCUMFLEX' },
{ hex: '008D', meaning: 'REVERSE LINE FEED' },
{ hex: '0076', meaning: 'LATIN SMALL LETTER V' },
{ hex: '00EB', meaning: 'LATIN SMALL LETTER E DIAERESIS' },
{ hex: '008E', meaning: 'SINGLE SHIFT TWO' },
{ hex: '007A', meaning: 'LATIN SMALL LETTER Z' }],
[{ hex: '00DB', meaning: 'LATIN CAPITAL LETTER U CIRCUMFLEX' },
{ hex: '008D', meaning: 'REVERSE LINE FEED' },
{ hex: '0076', meaning: 'LATIN SMALL LETTER V' },
{ hex: '00F7', meaning: 'DIVISION SIGN' },
{ hex: '008D', meaning: 'REVERSE LINE FEED' },
{ hex: '0036', meaning: 'DIGIT SIX' }],
[{ hex: '00DB', meaning: 'LATIN CAPITAL LETTER U CIRCUMFLEX' },
{ hex: '008D', meaning: 'REVERSE LINE FEED' },
{ hex: '0076', meaning: 'LATIN SMALL LETTER V' },
{ hex: '00F7', meaning: 'DIVISION SIGN' },
{ hex: '008E', meaning: 'SINGLE SHIFT TWO' },
{ hex: '0075', meaning: 'LATIN SMALL LETTER U' }],
[{ hex: '00DB', meaning: 'LATIN CAPITAL LETTER U CIRCUMFLEX' },
{ hex: '008D', meaning: 'REVERSE LINE FEED' },
{ hex: '0077', meaning: 'LATIN SMALL LETTER W' },
{ hex: '00D7', meaning: 'MULTIPLICATION SIGN' },
{ hex: '006E', meaning: 'LATIN SMALL LETTER N' },
{ hex: '00FB', meaning: 'LATIN SMALL LETTER U CIRCUMFLEX' }],
[{ hex: '00DB', meaning: 'LATIN CAPITAL LETTER U CIRCUMFLEX' },
{ hex: '008D', meaning: 'REVERSE LINE FEED' },
{ hex: '0077', meaning: 'LATIN SMALL LETTER W' },
{ hex: '00DB', meaning: 'LATIN CAPITAL LETTER U CIRCUMFLEX' },
{ hex: '005D', meaning: 'CLOSING SQUARE BRACKET' },
{ hex: '00B6', meaning: 'PARAGRAPH SIGN' }],
[{ hex: '00DB', meaning: 'LATIN CAPITAL LETTER U CIRCUMFLEX' },
{ hex: '008D', meaning: 'REVERSE LINE FEED' },
{ hex: '0077', meaning: 'LATIN SMALL LETTER W' },
{ hex: '00EB', meaning: 'LATIN SMALL LETTER E DIAERESIS' },
{ hex: '006E', meaning: 'LATIN SMALL LETTER N' },
{ hex: '0079', meaning: 'LATIN SMALL LETTER Y' }],
[{ hex: '00DB', meaning: 'LATIN CAPITAL LETTER U CIRCUMFLEX' },
{ hex: '008D', meaning: 'REVERSE LINE FEED' },
{ hex: '0077', meaning: 'LATIN SMALL LETTER W' },
{ hex: '00EF', meaning: 'LATIN SMALL LETTER I DIAERESIS' },
{ hex: '007F', meaning: 'DELETE' },
{ hex: '003D', meaning: 'EQUALS SIGN' }],
[{ hex: '00DB', meaning: 'LATIN CAPITAL LETTER U CIRCUMFLEX' },
{ hex: '008D', meaning: 'REVERSE LINE FEED' },
{ hex: '0077', meaning: 'LATIN SMALL LETTER W' },
{ hex: '00F7', meaning: 'DIVISION SIGN' },
{ hex: '007E', meaning: 'TILDE' },
{ hex: '0074', meaning: 'LATIN SMALL LETTER T' }],
[{ hex: '00DB', meaning: 'LATIN CAPITAL LETTER U CIRCUMFLEX' },
{ hex: '008D', meaning: 'REVERSE LINE FEED' },
{ hex: '0077', meaning: 'LATIN SMALL LETTER W' },
{ hex: '00F7', meaning: 'DIVISION SIGN' },
{ hex: '00AE', meaning: 'REGISTERED TRADE MARK SIGN' },
{ hex: '003A', meaning: 'COLON' }]]